// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SealedHelperServer.DBContexts;

namespace SealedHelperServer.Migrations
{
    [DbContext(typeof(DeckContext))]
    partial class DeckContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("SealedHelperServer.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("SealedHelperServer.Models.CardData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CardId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeckId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("DeckId");

                    b.ToTable("CardData");
                });

            modelBuilder.Entity("SealedHelperServer.Models.Deck", b =>
                {
                    b.Property<string>("DeckId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ActionCount")
                        .HasColumnType("INTEGER");

                    b.Property<float>("AemberControl")
                        .HasColumnType("REAL");

                    b.Property<int>("Aerc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Antisynergy")
                        .HasColumnType("INTEGER");

                    b.Property<float>("ArtifactControl")
                        .HasColumnType("REAL");

                    b.Property<int>("ArtifactCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Chains")
                        .HasColumnType("INTEGER");

                    b.Property<float>("CreatureControl")
                        .HasColumnType("REAL");

                    b.Property<int>("CreatureCount")
                        .HasColumnType("INTEGER");

                    b.Property<float>("CreatureProtection")
                        .HasColumnType("REAL");

                    b.Property<float>("Disruption")
                        .HasColumnType("REAL");

                    b.Property<int>("EffectivePower")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Efficiency")
                        .HasColumnType("REAL");

                    b.Property<int>("Expansion")
                        .HasColumnType("INTEGER");

                    b.Property<float>("ExpectedAember")
                        .HasColumnType("REAL");

                    b.Property<int>("House_0")
                        .HasColumnType("INTEGER");

                    b.Property<int>("House_1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("House_2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Loses")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<float>("Other")
                        .HasColumnType("REAL");

                    b.Property<int>("PowerLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RawAember")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Recursion")
                        .HasColumnType("REAL");

                    b.Property<int>("Sas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Synergy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UpgradeCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wins")
                        .HasColumnType("INTEGER");

                    b.HasKey("DeckId");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("SealedHelperServer.Models.CardData", b =>
                {
                    b.HasOne("SealedHelperServer.Models.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId");

                    b.HasOne("SealedHelperServer.Models.Deck", null)
                        .WithMany("Cards")
                        .HasForeignKey("DeckId");

                    b.Navigation("Card");
                });

            modelBuilder.Entity("SealedHelperServer.Models.Deck", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
